using JDownloader.Cli.Commands.Shared;
using JDownloader.Cli.Runtime;
using JDownloader.Cli.Transport;

namespace JDownloader.Cli.Commands.Accounts;

public abstract class AccountsCommandBase : FixedRequestPlanCommand
{
    protected AccountsCommandBase(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { }
}

public sealed class AccountsListCommand : AccountsCommandBase { public AccountsListCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.list"; protected override string Endpoint => "/accountsV2/listAccounts"; }
public sealed class AccountsGetCommand : AccountsCommandBase { public AccountsGetCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.get"; protected override string Endpoint => "/accountsV2/getPremiumHosterUrl"; }
public sealed class AccountsAddCommand : AccountsCommandBase { public AccountsAddCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.add"; protected override string Endpoint => "/accountsV2/addAccount"; protected override bool Destructive => true; }
public sealed class AccountsUpdateCommand : AccountsCommandBase { public AccountsUpdateCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.update"; protected override string Endpoint => "/accountsV2/setUserNameAndPassword"; protected override bool Destructive => true; }
public sealed class AccountsEnableCommand : AccountsCommandBase { public AccountsEnableCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.enable"; protected override string Endpoint => "/accountsV2/enableAccounts"; protected override bool Destructive => true; }
public sealed class AccountsDisableCommand : AccountsCommandBase { public AccountsDisableCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.disable"; protected override string Endpoint => "/accountsV2/disableAccounts"; protected override bool Destructive => true; }
public sealed class AccountsRemoveCommand : AccountsCommandBase { public AccountsRemoveCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.remove"; protected override string Endpoint => "/accountsV2/removeAccounts"; protected override bool Destructive => true; }
public sealed class AccountsRefreshCommand : AccountsCommandBase { public AccountsRefreshCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.refresh"; protected override string Endpoint => "/accountsV2/refreshAccounts"; protected override bool Destructive => true; }
public sealed class AccountsHostersListCommand : AccountsCommandBase { public AccountsHostersListCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.hosters.list"; protected override string Endpoint => "/accountsV2/listPremiumHoster"; }
public sealed class AccountsHostersUrlsCommand : AccountsCommandBase { public AccountsHostersUrlsCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.hosters.urls"; protected override string Endpoint => "/accountsV2/listPremiumHosterUrls"; }
public sealed class AccountsBasicAuthListCommand : AccountsCommandBase { public AccountsBasicAuthListCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.basic-auth.list"; protected override string Endpoint => "/accountsV2/listBasicAuth"; }
public sealed class AccountsBasicAuthAddCommand : AccountsCommandBase { public AccountsBasicAuthAddCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.basic-auth.add"; protected override string Endpoint => "/accountsV2/addBasicAuth"; protected override bool Destructive => true; }
public sealed class AccountsBasicAuthUpdateCommand : AccountsCommandBase { public AccountsBasicAuthUpdateCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.basic-auth.update"; protected override string Endpoint => "/accountsV2/updateBasicAuth"; protected override bool Destructive => true; }
public sealed class AccountsBasicAuthRemoveCommand : AccountsCommandBase { public AccountsBasicAuthRemoveCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "accounts.basic-auth.remove"; protected override string Endpoint => "/accountsV2/removeBasicAuths"; protected override bool Destructive => true; }
