using JDownloader.Cli.Commands.Shared;
using JDownloader.Cli.Runtime;
using JDownloader.Cli.Transport;

namespace JDownloader.Cli.Commands.Grabber;

public abstract class GrabberCommandBase : FixedRequestPlanCommand
{
    protected GrabberCommandBase(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { }
}

public sealed class GrabberAddCommand : GrabberCommandBase { public GrabberAddCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.add"; protected override string Endpoint => "/linkgrabberv2/addLinks"; protected override bool Destructive => true; }
public sealed class GrabberAddContainerCommand : GrabberCommandBase { public GrabberAddContainerCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.add-container"; protected override string Endpoint => "/linkgrabberv2/addContainer"; protected override bool Destructive => true; }
public sealed class GrabberClearCommand : GrabberCommandBase { public GrabberClearCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.clear"; protected override string Endpoint => "/linkgrabberv2/clearList"; protected override bool Destructive => true; }
public sealed class GrabberMoveToDownloadsCommand : GrabberCommandBase { public GrabberMoveToDownloadsCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.move-to-downloads"; protected override string Endpoint => "/linkgrabberv2/moveToDownloadlist"; protected override bool Destructive => true; }
public sealed class GrabberLinksListCommand : GrabberCommandBase { public GrabberLinksListCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.links.list"; protected override string Endpoint => "/linkgrabberv2/queryLinks"; }
public sealed class GrabberLinksRemoveCommand : GrabberCommandBase { public GrabberLinksRemoveCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.links.remove"; protected override string Endpoint => "/linkgrabberv2/removeLinks"; protected override bool Destructive => true; }
public sealed class GrabberPackagesListCommand : GrabberCommandBase { public GrabberPackagesListCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.packages.list"; protected override string Endpoint => "/linkgrabberv2/queryPackages"; }
public sealed class GrabberPackagesRemoveCommand : GrabberCommandBase { public GrabberPackagesRemoveCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.packages.remove"; protected override string Endpoint => "/linkgrabberv2/removePackages"; protected override bool Destructive => true; }
public sealed class GrabberJobsListCommand : GrabberCommandBase { public GrabberJobsListCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.jobs.list"; protected override string Endpoint => "/linkgrabberv2/queryLinkCrawlerJobs"; }
public sealed class GrabberJobsGetCommand : GrabberCommandBase { public GrabberJobsGetCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.jobs.get"; protected override string Endpoint => "/linkgrabberv2/getPackageCount"; }
public sealed class GrabberVariantsListCommand : GrabberCommandBase { public GrabberVariantsListCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.variants.list"; protected override string Endpoint => "/linkgrabberv2/getVariants"; }
public sealed class GrabberVariantsSetCommand : GrabberCommandBase { public GrabberVariantsSetCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "grabber.variants.set"; protected override string Endpoint => "/linkgrabberv2/setVariant"; protected override bool Destructive => true; }
