using JDownloader.Cli.Commands.Shared;
using JDownloader.Cli.Runtime;
using JDownloader.Cli.Transport;

namespace JDownloader.Cli.Commands.System;

public abstract class SystemCommandBase : FixedRequestPlanCommand
{
    protected SystemCommandBase(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { }
}

public sealed class SystemInfoCommand : SystemCommandBase { public SystemInfoCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.info"; protected override string Endpoint => "/system/getSystemInfo"; }
public sealed class SystemStorageCommand : SystemCommandBase { public SystemStorageCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.storage"; protected override string Endpoint => "/system/getStorageInfos"; }
public sealed class SystemReconnectCommand : SystemCommandBase { public SystemReconnectCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.reconnect"; protected override string Endpoint => "/reconnect/doReconnect"; protected override bool Destructive => true; }
public sealed class SystemJdVersionCommand : SystemCommandBase { public SystemJdVersionCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.jd.version"; protected override string Endpoint => "/jd/getVersion"; }
public sealed class SystemJdRevisionCommand : SystemCommandBase { public SystemJdRevisionCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.jd.revision"; protected override string Endpoint => "/jd/getRevision"; }
public sealed class SystemJdUptimeCommand : SystemCommandBase { public SystemJdUptimeCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.jd.uptime"; protected override string Endpoint => "/jd/uptime"; }
public sealed class SystemJdRefreshPluginsCommand : SystemCommandBase { public SystemJdRefreshPluginsCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.jd.refresh-plugins"; protected override string Endpoint => "/jd/refreshPlugins"; protected override bool Destructive => true; }
public sealed class SystemJdRestartCommand : SystemCommandBase { public SystemJdRestartCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.jd.restart"; protected override string Endpoint => "/jd/restart"; protected override bool Destructive => true; }
public sealed class SystemJdExitCommand : SystemCommandBase { public SystemJdExitCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.jd.exit"; protected override string Endpoint => "/jd/exit"; protected override bool Destructive => true; }
public sealed class SystemOsShutdownCommand : SystemCommandBase { public SystemOsShutdownCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.os.shutdown"; protected override string Endpoint => "/system/shutdownOS"; protected override bool Destructive => true; }
public sealed class SystemOsHibernateCommand : SystemCommandBase { public SystemOsHibernateCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.os.hibernate"; protected override string Endpoint => "/system/hibernateOS"; protected override bool Destructive => true; }
public sealed class SystemOsStandbyCommand : SystemCommandBase { public SystemOsStandbyCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.os.standby"; protected override string Endpoint => "/system/standbyOS"; protected override bool Destructive => true; }
public sealed class SystemUpdateCheckCommand : SystemCommandBase { public SystemUpdateCheckCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.update.check"; protected override string Endpoint => "/update/isUpdateAvailable"; }
public sealed class SystemUpdateRunCommand : SystemCommandBase { public SystemUpdateRunCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.update.run"; protected override string Endpoint => "/update/runUpdateCheck"; protected override bool Destructive => true; }
public sealed class SystemUpdateRestartCommand : SystemCommandBase { public SystemUpdateRestartCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.update.restart"; protected override string Endpoint => "/update/restartAndUpdate"; protected override bool Destructive => true; }
public sealed class SystemToggleCommand : SystemCommandBase { public SystemToggleCommand(IProfileResolver a, IOutputRenderer b, IDiagnosticLogger c, IMyJdTransport d, IConfirmationGuard e) : base(a, b, c, d, e) { } protected override string Operation => "system.toggle"; protected override string Endpoint => "/system/toggle"; protected override bool Destructive => true; }
